### ISSUE TITLE
住所の「ヨミガナ」も取得できると嬉しい

### ISSUE THREAD

**Issue by kakipo** [ninton/jquery.jpostal.js#10]
とても便利なプラグインの共有ありがとうございます。
現状の項目に加え、住所の「ヨミガナ」も取得できると大変嬉しいです。

# 現状

|書式|項目|
|---|---|
|%3|都道府県|
|%4|市区町村|
|%5|町域|
|%6|大口事業所の番地|
|%7|大口事業所の名称|

# 要望（案）

|書式|項目|
|---|---|
|%3|都道府県|
|%4|市区町村|
|%5|町域|
|%6|大口事業所の番地|
|%7|大口事業所の名称|
|%8|都道府県（カナ）|
|%9|市区町村（カナ）|
|%10|町域（カナ）|

**Comment by ninton** [comment]
ご要望ありがとうございます。
通常の市区町村や町域の不要部分の削除に力尽き、カナまで手をつけなかった覚えがあります。
できるところから実装したいと思います。

**Comment by ninton** [comment]
ver/2.5をコミットしました。
都道府県カナ、市区町村カナを取得できるようになりました。
jpostal.googlecode.comにもコミット済みです。

**Comment by kakipo** [comment]
:+1: :+1:

**Comment by ninton** [comment]
ver/2.6をコミットしました。
町域カナを取得できるようになりました。
jpostal.googlecode.comにもコミット済みです。

**Comment by kakipo** [comment]
素晴らしい！
ありがとうございます :clap:
