### ISSUE TITLE
[お知らせ] 新サーバ：jpostal-1006.appspot.com

### ISSUE THREAD

**Issue by ninton** [ninton/jquery.jpostal.js#12]
jpostalの設置サーバをjpostal-1006.appspot.comに変更しました。
これからご利用の場合は、README.txtを読んでください。

すでにjpostal.googlecode.com/svn/trunk/jquery.jpostal.jsをご利用の場合、
HTMLを次のように修正してください。
修正前
&lt;script src="//jpostal.googlecode.com/svn/trunk/jquery.jpostal.js"&gt;
修正後
&lt;script src="//jpostal-1006.appspot.com/jquery.jpostal.js"&gt;

jpostal.googlecode.com は郵便データ2015-06-30版のままとし、GoogleCodeサービス終了まで継続します。

**Comment by kurotaky** [comment]
@ninton 
はじめまして、普段から `jquery.jpostal.js` を利用させていただいております。
いつもメンテナンスありがとうございます。

修正後は `//jpostal-1006.appspot.com/jpostal.jquery.js` ではなく、
`//jpostal-1006.appspot.com/jquery.jpostal.js` となるようです。
ご確認よろしくお願いします 😃

**Comment by ninton** [comment]
@kurotaky 
コメントありがとうございます、助かります。
修正しました。

**Comment by kurotaky** [comment]
修正確認しました 👍
