### ISSUE TITLE
503 Over Quota on jpostal-1006.appspot.com

### ISSUE THREAD

**Issue by kmurakami** [ninton/jquery.jpostal.js#16]
jpostal-1006.appspot.com にて 503 Over Quota が発生しています。当ライブラリを長らく利用させていただいておりますが、当事象は今回が初めてです。利用者が増え、アクセス数が増えたことが Over Quota の原因だと推測しております。Quota のリミット上限を上げる予定はございますでしょうか？

![screen shot 2016-09-13 at 9 08 43 am](https://cloud.githubusercontent.com/assets/5222769/18481762/4610cd74-7992-11e6-8971-6e8471d6440a.png)

**Comment by ninton** [comment]
とりいそぎ1日の割り当てを増やしました。
ご連絡ありがとうございました。

**Comment by kmurakami** [comment]
503 が解消されていることを確認しました。

ありがとうございました。
