### ISSUE TITLE
761-3110 の町域が取得できない

### ISSUE THREAD

**Issue by mitsu-ksgr** [ninton/jquery.jpostal.js#17]
便利なプラグインありがとうございます！！

表題の```761-3110```という郵便番号のときに、町域が取得出来ないようです。

住所：761-3110 香川県 香川郡直島町 直島町一円
http://www.post.japanpost.jp/cgi-zip/zipcode.php?zip=7613110

### 現状の結果
- 郵便番号： 761-3110
- 都道府県： 香川県
- 市区町村： 香川郡直島町
- 町域：
- 都道府県カナ： ｶｶﾞﾜｹﾝ
- 市区町村カナ： ｶｶﾞﾜｸﾞﾝﾅｵｼﾏﾁｮｳ
- 町域カナ： _

### 求める結果
- 郵便番号： 761-3110
- 都道府県： 香川県
- 市区町村： 香川郡直島町
- 町域： 直島町一円
- 都道府県カナ： ｶｶﾞﾜｹﾝ
- 市区町村カナ： ｶｶﾞﾜｸﾞﾝﾅｵｼﾏﾁｮｳ
- 町域カナ： ﾅｵｼﾏﾁｮｳｲﾁｴﾝ

2017/08/08 14時時点の http://jpostal-1006.appspot.com/sample_1.html で確認しました。

**Comment by ninton** [comment]
詳細ありがとうございます。
こちらでも再現しました。
さっそく調査します。

**Comment by ninton** [comment]
これはjpostalの仕様でした。
「現状の結果」が仕様どおりの動作です。

日本郵便データからjpostal用にデータ変換する際に、
町域の「一円」を残すか、空欄にするかを処理しています。
https://github.com/ninton/cakephp.jpostal/blob/master/Lib/JpostalConverter.phpの94行目です。

(1) 町域が「○○○一円」の場合は、空欄にします。
ご指摘の761-3110の他、多数あります。
例：7170201
岡山県 真庭郡新庄村 新庄村一円
↓
岡山県 真庭郡新庄村

(2) 町域が「一円」の場合は、「一円」という地名なので、残します。
例：5220317 滋賀県 犬上郡多賀町一円

**Comment by mitsu-ksgr** [comment]
@ninton 
調査・返答ありがとうございます！
なるほど、「一円」とはその地域を指すものだったのですね。
すみません、知りませんでした 💦 

でしたら空欄が正しい動作だと思いますので、このままクローズさせて頂きます。
ありがとうございました！！
