### ISSUE TITLE
npmモジュールの公開について

### ISSUE THREAD

**Issue by y-yagi** [ninton/jquery.jpostal.js#19]
便利なプラグインありがとうございます！ 

こちらのプラグインは現状[npm](https://www.npmjs.com/)に公開されていないように見受けられましたが、
npmモジュールにしてnpmに公開されるご予定はありますでしょうか? 

今関わっているプロジェクトでは、JSのライブラリの管理にyarnを使っており、
可能ならこちらのプラグインも同じ形で管理できればと思い、ご質問させて頂きました。

**Comment by ninton** [comment]
リクエストありがとうございます。
jquery-jpostal-ja で、npm公開準備中です。
調整中ですので、数日お待ちください。

**Comment by ninton** [comment]
ver/2.9.8でnpmにリリースしました。
npmについての説明は、READMEの最後に追記しました。
npm公開は初めてなので、おかしいところがあったら、遠慮なくお知らせください。

**Comment by y-yagi** [comment]
ご対応有難うございます！

手元で確認した限り、問題なさそうに見えましたので、こちらクローズさせていただきます。有難うございますした！
