### ISSUE TITLE
README.txt：「npm 使用例」のパッケージ名の TYPO

### ISSUE THREAD

**Issue by dreamseeker** [ninton/jquery.jpostal.js#21]
有益なプラグインをありがとうございます。
折に触れ、利用させていただいています。

さて、表題の通り README.txt の「npm 使用例」ブロックに記載された
解説文やインストールコマンドなどのパッケージ名の表記に誤りがあることに気づきましたので、ご報告です。

```
誤） jpostal-jquery-ja
▼
正） jquery-jpostal-ja
```

お時間あるときにご確認ください。

**Comment by ninton** [comment]
ご連絡ありがとうございます。
以前も似たようなTYPOをしたことがあり、またやってしまいました。
さっそく修正してgithubにpush、npmにpublishしました。

**Comment by dreamseeker** [comment]
早々のご対応、ありがとうございます！
この issue は close しますね。
