### ISSUE TITLE
ajaxにおけるsyncの警告

### ISSUE THREAD

**Issue by dd-keiichi** [ninton/jquery.jpostal.js#27]
いつも使わせて頂いていて助かっています。

実行時、以下の警告がコンソールに表示されてしまいます。

> [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

（chrome バージョン: 68.0.3440.106で確認）

データファイル取得時にajaxオプションに `{ async: false }` を渡していることが原因だと思われます。
ご確認よろしくお願いします。

**Comment by ninton** [comment]
ご意見ありがとうございます。
警告は承知していまして、非同期のテストケースは面倒かな、といった理由だったと思います。
async: trueでテストを試してみます。

**Comment by ninton** [comment]
@dd-keiichi
async: trueで、テストとおりました。
ver/2.12をリリースしました。

**Comment by dd-keiichi** [comment]
迅速なご対応ありがとうございます！
