### ISSUE TITLE
新しい住所への対応依頼

### ISSUE THREAD

**Issue by YujiMiyashita** [ninton/jquery.jpostal.js#48]
5/4に下記住所が新しく日本に追加されたようです。

```
417-0856
静岡県富士市さんどまき
```

現状郵便番号を入力すると `静岡県富士市` までしか取得できないため、 `静岡県富士市さんどまき` まで取得できるようご対応お願いできますでしょうか？

参考
https://www.city.fuji.shizuoka.jp/sp/page/rn2ola000002gl0i.html

**Comment by ninton** [comment]
ご連絡ありがとうございます。
次回のJpostal更新時に追加されると思います。

Jpostalは、日本郵便の全国一括データを利用しています。
https://www.post.japanpost.jp/zipcode/dl/kogaki-zip.html

日本郵便のダウンロードデータは、およそ月末の27〜31日に更新されています。
（次回の更新予定は明記されていません）
先月は 4/30 更新でした。
さきほど、静岡県、全国一括、どちらもダウンロードして確認したところ、
残念ながら、4170856 は含まれていませんでした。

今月5月下旬の更新で、417-0856が追加されれば、
6/1のJpostalデータ更新で反映されると思います。

**Comment by YujiMiyashita** [comment]
@ninton 
>今月5月下旬の更新で、417-0856が追加されれば、6/1のJpostalデータ更新で反映されると思います。

かしこまりました。日本郵便の対応待ちということですね。
こちらのissueはクローズさせていただきます。
ご回答ありがとうございました。

**Comment by ninton** [comment]
@YujiMiyashita

417-0856 富士市さんどまき、追加されました。
（返信不要です）
