### ISSUE TITLE
Q: Identify invalid postcodes

### ISSUE THREAD

**Issue by RossellaFer** [ninton/jquery.jpostal.js#50]
Hi, first of all, great job with the library! 

I have read about the default when searching for an postcode, but I was wondering if there is a method to identify when a postcode does not exist, so that an error message can be displayed in the front end

    //    --------------------------------------------------
    //    i_postcode    find()    find()    result
    //                1234567    123
    //    --------------------------------------------------
    //    1             -        -        defaults
    //    12            -        -        defaults
    //    123           -        Y        find( '123' )
    //    123           -        N        defaults
    //    1234          -        Y        find( '123' )
    //    1234          -        N        defaults
    //    1234567       Y        -        find( '1234567' )
    //    1234567       N        Y        find( '123' )
    //   1234567       N        N        defaults
       --------------------------------------------------

**Comment by RossellaFer** [comment]
Right now the solution I am using is checking if the `jPostalSelector[address1Sel] = '%5';` is empty but the jPostalSelector[citySel] =  '%4'; has a value when the postcode length is 7, but as you can imagine this is not a very strong solution

**Comment by ninton** [comment]
Hello, Thank you for the question.
My name is Aoki from Ninton.

It is not possible to detect that the postcode does not exist.

As you might think, it cannot be detected if the addressCell is blank.

For example, 999-7700 is an existing zip code, but addressCell is blank.

```
prefecture = '山形県'
city = '東田川郡庄内町'
address = ''
```

**Comment by ninton** [comment]
The idea is to add the strict7match flag.

Normally, the strict7match flag is off and the process is normal. That is, if it does not exist, it returns data for a 3-digit match.

If the strict7match flag is on
If the 7 digits do not actually exist, all blanks are returned.

If you like this idea, we'll implement it in the next update.

**Comment by RossellaFer** [comment]
Thank you so much, Aoki!

It would be great to have this functionality, so that there is a visual feedback for the user if the postcode does not exist. 
Do you have an initial idea about the timeframe for the next update to be released?

**Comment by ninton** [comment]
I pushed to personals/aoki/develop branch.

Please see test/sample_9.html : 34 - 43 line

If you enter 999-9999, the console will display "存在しない郵便番号です".


```
		strict7Match: true,
	});

	$("#address1").on("change", function() {
		var val = $("#address1").val();
		var len = $("#postcode1").val().length + $("#postcode2").val().length;
		if (val === "" && len === 7) {
			console.log('存在しない郵便番号です');
		}
	});

```

**Comment by ninton** [comment]
I will make a test case from now on.

It will be released by tomorrow morning.

**Comment by RossellaFer** [comment]
The implementation is clear and thank you for the fast resolution to my query, Aoki!

**Comment by ninton** [comment]
ver / 2.14.0 has been released 😀

You can check it at https://jpostal-1006.appspot.com/sample_9.html

If you enter 999-9999, "存在しない郵便番号です" will be displayed in the onchange_2 input field.

**Comment by RossellaFer** [comment]
Thank you so much! 
I was able to implement this in my project 😀
