### ISSUE TITLE
「Uncaught TypeError: $(...).get(...) is undefined」エラー

### ISSUE THREAD

**Issue by AppKim** [ninton/jquery.jpostal.js#52]
とても便利なプラグインありがとうございます。
一点教えていただきたいことがございます。

以下のように実装し使おうとしておりますが、

「Uncaught TypeError: $(...).get(...) is undefined」エラーが発生します。
AddressProvince  : '%3'でエラーになっているかは分かりましたが、対策が分からず・・。
因みに、AddressProvinceを「'#AddressProvince_5517543866559（AddressProvinceのvalue値)'」に変更すれば上手く動きます。
対策がありますでしょうか。

    $('.address-edit').on('input',function(evt){
        var formId = evt.target.dataset.formId;
        var target =  '#'+'AddressZip_'+ formId;
        var AddressProvince = '#'+'AddressProvince_' + formId;
        $(target).jpostal({
          postcode : [
            target,	
          ],
          address : {
            AddressProvince  : '%3',	
          }
        });
      });

**Comment by ninton** [comment]
@AppKim 
お問合わせありがとうございます。

ぼくも試したところ、同じエラーになりました。

次に、次のようなことを試しました。
```
var formId = 5517543866559;
var AddressProvince = '#'+'AddressProvince_' + formId;
var config = {
      address : {
        AddressProvince  : '%3',	
      }
    };
console.log(Object.keys(config.address));
```
すると、コンソールには、

```
Array [ "AddressProvince" ]
```
と表示されました。

つまり、JSON表現のキーは、ダブルクォートやシングルクォートでクォートしていなくても、変数としてではなく、文字列としてパースされます。


そこで、次のように書いてはどうでしょうか。

```
$('.address-edit').on('input',function(evt){
    var formId = evt.target.dataset.formId;
    var target =  '#'+'AddressZip_'+ formId;
    var AddressProvince = '#'+'AddressProvince_' + formId;

    var config = {
      postcode : [
        target,	
      ],
      address : {
      }
    };
    config.address[AddressProvince] = '%3';

    $(target).jpostal(config);
```

**Comment by AppKim** [comment]
早々に対応していただきありがとうございます！

> つまり、JSON表現のキーは、ダブルクォートやシングルクォートでクォートしていなくても、変数としてではなく、文字列としてパースされます。

なるほど！
提案していただいた方法で解決できました！
とても助かりました！
ありがとうございます。
