### ISSUE TITLE
郵便番号9200381が重複している

### ISSUE THREAD

**Issue by mryoshio** [ninton/jquery.jpostal.js#53]
便利なプラグインの開発・運用ありがとうございます ❗ 

最近、920.json内の同一郵便番号に2つの住所が紐付いていることに気づきました。

```
# https://jpostal-1006.appspot.com/json/920.json?のレスポンスから抜粋

- 217: ["_9200381", "石川県", "金沢市", "古府", "３丁目１２", "北菱電興　株式会社", "ｲｼｶﾜｹﾝ", "ｶﾅｻﾞﾜｼ", "ｺﾌﾞ"]
- 218: ["_9200381", "石川県", "金沢市", "中屋", "", "", "ｲｼｶﾜｹﾝ", "ｶﾅｻﾞﾜｼ", "ﾅｶﾔ"]
```

https://www.post.japanpost.jp/cgi-zip/zipcode.php?zip=920-0381 を見るに中屋が正しいのですが、現状の挙動ではフォームに「古府」の方で自動入力されるようになっています。

こちらご対応頂くことは可能でしょうか ❓ 

（920.json変更のPRを作りかけたのですが、自動で取ってきている流れとコンフリクトする可能性が高いと考え止めました）

**Comment by hideaki-take** [comment]
@ninton 
jpostal のライブラリを活用させていただいている者です。
便利なライブラリのご運用ありがとうございます。

郵便番号から参照される住所情報に誤りがあることに気づき、このスレッドに行き着きました。

投稿者が記載されていることと同じ事象が確認され、私も困っている次第です。
お忙しいかと存じますが、ご確認ならびにご対応いただけますと幸いです。

どうぞよろしくお願いいたします。

**Comment by ninton** [comment]
コメントありがとうございます

大口事業所csvに、たしかに
```
["_9200381", "石川県", "金沢市", "古府", "３丁目１２", "北菱電興　株式会社", "ｲｼｶﾜｹﾝ", "ｶﾅｻﾞﾜｼ", "ｺﾌﾞ"]
```
があり、

通常の郵便番号としては、
```
 ["_9200381", "石川県", "金沢市", "中屋", "", "", "ｲｼｶﾜｹﾝ", "ｶﾅｻﾞﾜｼ", "ﾅｶﾔ"]
```
のほうが正しいようです。

ここの並べ方を変えないかぎり、古府を表示してしまいますね。

郵便データのソート順を考えます。

**Comment by ninton** [comment]
https://github.com/ninton/jpostal_json/pull/2/files
で対応しました。

修正済みの json が 
http://jpostal-1006.appspot.com/sample_1.html
にもリリース済みです。
